export const DRILL_FIELDS = [
  { name: 'full_drill_block', label: 'Paste Full Drill Block' },
  { name: 'name', label: 'Name' },
  { name: 'simple_name', label: 'Simple Name' },
  { name: 'purpose', label: 'Purpose' },
  { name: 'influences', label: 'Influences' },
  { name: 'difficulty', label: 'Difficulty' },
  { name: 'skill_demands', label: 'Skill Demands' },
  { name: 'equipment_requirements', label: 'Equipment Requirements' },
  { name: 'equipment_alternatives', label: 'Equipment Alternatives' },
  { name: 'execution_requirements', label: 'Execution Requirements' },
  { name: 'regressions', label: 'Regressions' },
  { name: 'progressions', label: 'Progressions' },
  { name: 'plane', label: 'Plane' },
  { name: 'chain_type', label: 'Chain Type' },
  { name: 'stance', label: 'Stance' },
  { name: 'movement_types', label: 'Movement Types' },
  { name: 'region', label: 'Region' },
  { name: 'joints', label: 'Joints' },
  { name: 'joint_actions', label: 'Joint Actions' },
  { name: 'muscles', label: 'Muscles' },
  { name: 'tendons', label: 'Tendons' },
  { name: 'nervous_system', label: 'Nervous System' },
  { name: 'psychological', label: 'Psychological' },
  { name: 'system_impact', label: 'System Impact' }
];
